### ISSUE TITLE
[Bug]: Diagonal Windows causes incompatibilty between WorldEdit and Hephaestus

### ISSUE THREAD

**Issue by JMackey1** [Fuzss/diagonalwindows#6]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

I've written tickets for the other mods here, which include details:

https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/77
https://github.com/EngineHub/WorldEdit/issues/2414

**Comment by JMackey1** [comment]
The issue is worse with 8.1.0. Now it causes the game to crash. It and Diagonal Fences cause an insane amount of logging (400 MB+).

**Comment by Fuzss** [comment]
Please provide the crash report.

**Comment by JMackey1** [comment]
[crash-2023-10-27_16.27.32-client.txt](https://github.com/Fuzss/diagonalwindows/files/13193072/crash-2023-10-27_16.27.32-client.txt)

It mentions PuzzlesLib specifically, and I am having crashes when loading a world even with the Diagonal mods disabled. Going to try rolling back PuzzlesLib and see if that fixes it.

**Comment by Fuzss** [comment]
Ah, so your crash is an incompatibility with Star (library for the tinkers port). That should probably be resolved on their end.
https://github.com/AlphaMode/Star/issues/2

**Comment by JMackey1** [comment]
Thanks, that seems to be the case. With the latest version of PuzzlesLib/Diagonal Windows/Diagonal Fences, but Hephaestus (Tinkers port) disabled, the game loads correctly. Still getting a ton of logs from the Diagonal mods, though.

**Comment by Fuzss** [comment]
Can you just post a line as an example? And can you see textures for the diagonal blocks in-game?

**Comment by JMackey1** [comment]
Tons of messages that look like this:

[16:41:35] [Worker-ResourceReload-11/ERROR]: Failed to modify unbaked model before bake
java.lang.IllegalArgumentException: invalid model for diagonal block: diagonalfences:betterend/tenanea_fence#east=false,north=false,north_east=false,north_west=true,south=false,south_east=true,south_west=false,waterlogged=false,west=false
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.makeMultiPart(MultiPartTranslator.java:80) ~[diagonalblocks-8.0.0-500a37c7bb998e2b.jar:?]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.getModelFromBase(MultiPartTranslator.java:73) ~[diagonalblocks-8.0.0-500a37c7bb998e2b.jar:?]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.apply(MultiPartTranslator.java:69) ~[diagonalblocks-8.0.0-500a37c7bb998e2b.jar:?]
	at fuzs.diagonalblocks.client.handler.DiagonalModelHandler.onModifyUnbakedModel(DiagonalModelHandler.java:40) ~[diagonalblocks-8.0.0-500a37c7bb998e2b.jar:?]
	at fuzs.puzzleslib.impl.client.event.FabricClientEventInvokers.lambda$register$71(FabricClientEventInvokers.java:370) ~[PuzzlesLib-v8.1.2-1.20.1-Fabric.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$4(ModelLoaderPluginContextImpl.java:86) ~[fabric-model-loading-api-v1-1.0.+709a987177-148c05fd9fd2fb0f.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelBeforeBake(ModelLoadingEventDispatcher.java:276) ~[fabric-model-loading-api-v1-1.0.+709a987177-148c05fd9fd2fb0f.jar:?]
	at net.minecraft.class_1088$class_7778.localvar$dlf000$fabric-model-loading-api-v1$invokeModifyBeforeBake(class_1088.java:553) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
	
What is the mod tag for these? I don't get any results for @diagonal in REI

**Comment by Fuzss** [comment]
They don't work like that. Just place vanilla fences/walls/glass panes.

**Comment by JMackey1** [comment]
![Untitled](https://github.com/Fuzss/diagonalwindows/assets/49456732/84fcf182-99e0-4b99-9ad8-b40574da8f0c)

Black and purple blocks are oak fences, the glass are glass blocks, glass panes have the same model as the fences.

**Comment by Fuzss** [comment]
Ok, thanks for helping out!

Now that's a mod conflict. Would be great if you could start removing other mods until it starts working. Doesn't seem to be another way to find the root of this unfortunately.

**Comment by Fuzss** [comment]
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.

This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:
Remove half of the existing things, and put them aside.
Run the program / game.
Does the issue still exist?
If YES: Repeat from step 1 with the current things.
IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
Repeat this process until the problematic thing/s have been found.

**Comment by JMackey1** [comment]
![Untitled](https://github.com/Fuzss/diagonalwindows/assets/49456732/e202a4f3-b650-4172-a8e0-3977bcafaa70)

This is a brand new world, nothing but Diagonal mods and dependencies enabled. I even disabled shaders and all data packs. These are glass panes, still have the heavy logging issue and no texture.

**Comment by JMackey1** [comment]
![Untitled1](https://github.com/Fuzss/diagonalwindows/assets/49456732/f26efcd0-a4e8-4b6a-a7f8-ed4528d7a334)

Downgraded to 8.0.1 and they work correctly, and the log issues are also resolved.

**Comment by Fuzss** [comment]
Fixed in latest version. Still would appreciate feedback on Hephasestus once Star is compatible with Puzzles Lib.

**Comment by AlphaMode** [comment]
Issue with star should be fixed, sorry about taking so long.
